;; GO
(require-package 'go-mode)
(require-package 'company-go)
(require-package 'go-projectile)
(require-package 'go-eldoc)
(require-package 'flycheck)
(add-hook 'go-mode-hook (lambda ()
			 (go-eldoc-setup)
			 (flycheck-mode)
			 (setq gofmt-command "goimports")
			 (add-hook 'before-save-hook 'gofmt-before-save)
			 (setq company-go-show-annotation t)
			 (set (make-local-variable 'company-backends) '(company-go))
			 (company-mode)))
